name: Android By Google
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps: 
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Set Up JDK
       uses: actions/setup-java@v2
       with:
         java-version: '17'
         distribution: 'temurin'

     - name: Permission
       run: chmod +x ./gradlew

     - name: Clean
       run: ./gradlew clean

     - name: Build with Gradle
       run: ./gradlew assembleDebug

     - name: List APK Directory
       run: ls app/build/outputs/apk/debug/

     - name: Upload APK
       uses: actions/upload-artifact@v4
       with:
         name: debug-apk
         path: app/build/outputs/apk/debug/app-debug.apk

     - name: Create Github Release
       id: create_release
       uses: softprops/action-gh-release@v1
       with:
        tag_name: v1.0.0
        files: app/build/outputs/apk/debug/app-debug.apk
       env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      
    
